version: "3"

vars:
  TERRAFORM_INFRA_DIR: "terraform"

tasks:
  deploy:
    desc: "Apply the infrastructure"
    cmds:
      - devbox run -- task terraform-apply

  destroy:
    desc: "Destroy the infrastructure"
    cmds:
      - devbox run -- task terraform-destroy

  terraform-apply:
    desc: "Apply Terraform configuration for ECS and related services"
    dir: "{{.TERRAFORM_INFRA_DIR}}"
    cmds:
      - terraform init -backend-config="backend.tfvars" 
      - terraform validate
      - terraform fmt
      - terraform plan -var-file=terraform.tfvars
      - terraform apply -var-file=terraform.tfvars --auto-approve

  terraform-destroy:
    desc: "Destroy Terrafrom Infra"
    dir: "{{.TERRAFORM_INFRA_DIR}}"
    cmds:
      - terraform init -backend-config="backend.tfvars"
      - terraform validate
      - terraform plan -var-file=terraform.tfvars
      - terraform destroy -var-file=terraform.tfvars --auto-approve
